### ISSUE TITLE
Wall of shame entry, submitted by pokemonfreak

### ISSUE THREAD

**Issue by nyanlathotep** [G00FBALL/not-a-wiki#18]
mocstigma10 is the offender, log is [here](https://pastebin.com/fpR7X1fQ)

**Comment by nyanlathotep** [comment]
this isn't funny and I don't believe he's serious, I would say don't include it
he may just be playing the part to get on the wall, and also asked to be on it, so I would vote against
but I'd like to see what everyone else has to say

**Comment by Namelessname9** [comment]
I vote against as well, not especially funny, and didn't even claim not to cheat or anything, mentioned one time he is R108 and never again, even admitted he isn't really R108 farely quickly.

**Comment by Alfik0** [comment]
i vote against as well

**Comment by G00FBALL** [comment]
No, he is just being silly and and now I will close this, Thank you for sending it to us.
