### ISSUE TITLE
Building "Alignements" needs to have its spelling fixed

### ISSUE THREAD

**Issue by neuapostolisch** [G00FBALL/not-a-wiki#57]

**Comment by G00FBALL** [comment]
it can be both ways 
http://www.dictionary.com/browse/alinement
1780-90; align + -ment; replacing earlier alignement < French

**Comment by schaefer-austin-p** [comment]
I have never seen "Alignement" used in my entire life; it's always just "Alignment".

**Comment by G00FBALL** [comment]
Maybe I am missing something, Do I have it spelled as  "Alignement"?
and if so where?

**Comment by mrbellek** [comment]
@G00FBALL  I think the page itself is at /BuildingAlign**e**ments but on the page itself it's spelled without the extra 'e'. :)

**Comment by G00FBALL** [comment]
ahh thank you , I never noticed that but fixing now

**Comment by G00FBALL** [comment]
fixed
